export const Config = {
    MENU_CALLBACK: 'MENU_CALLBACK', 
    PAYMENT_CALLBACK: 'PAYMENT_CALLBACK',
    MENTOR_CALLBACK: 'MENTOR_CALLBACK',
    ACCOUNT_CALLBACK: 'ACCOUNT_CALLBACK', 
    BOT_KEY: '',
}